/// <mls fileReference="_102048_/l1/buildFlowFsm/layer_1_external/adapters/http/controllers/createTimeLog.defs.ts" enhancement="_blank"/>

export const createTimeLogController = {
  "schemaVersion": "2026-06-26",
  "artifactType": "httpController",
  "artifactId": "createTimeLog",
  "moduleName": "buildFlowFsm",
  "status": "draft",
  "source": {
    "agentName": "agentCbHttpController",
    "stepId": 0,
    "planId": ""
  },
  "data": {
    "pageId": "createTimeLog",
    "controllerName": "CreateTimeLogController",
    "ownerKind": "operation",
    "outputSource": "usecase",
    "handlers": [
      {
        "handlerName": "buildFlowFsmCreateTimeLogHandler",
        "command": "createTimeLog",
        "usecaseRef": "createTimeLog",
        "inputTypeName": "CreateTimeLogInput",
        "kind": "create",
        "inputContract": [
          {
            "inputId": "workTaskId",
            "fieldRef": "TimeLog.workTaskId",
            "required": true,
            "source": "selectedEntity",
            "description": "The work task the field worker is logging hours against."
          },
          {
            "inputId": "workerId",
            "fieldRef": "TimeLog.workerId",
            "required": true,
            "source": "actorSession",
            "description": "The identifier of the field worker recording the hours, resolved from the authenticated session."
          },
          {
            "inputId": "logDate",
            "fieldRef": "TimeLog.logDate",
            "required": true,
            "source": "userInput",
            "description": "The calendar date on which the work was performed."
          },
          {
            "inputId": "hours",
            "fieldRef": "TimeLog.hours",
            "required": true,
            "source": "userInput",
            "description": "Number of hours worked on the task for this log entry."
          },
          {
            "inputId": "workerRate",
            "fieldRef": "TimeLog.workerRate",
            "required": true,
            "source": "actorSession",
            "description": "Hourly cost rate of the worker sourced from the platform user profile at the time of logging."
          },
          {
            "inputId": "timeLogId",
            "fieldRef": "TimeLog.timeLogId",
            "required": true,
            "source": "systemDefault",
            "description": "System-generated unique identifier for the new time log entry."
          },
          {
            "inputId": "status",
            "fieldRef": "TimeLog.status",
            "required": true,
            "source": "systemDefault",
            "description": "Initial lifecycle state of the time log, set to posted on creation."
          },
          {
            "inputId": "createdAt",
            "fieldRef": "TimeLog.createdAt",
            "required": true,
            "source": "systemDefault",
            "description": "Timestamp when the time log entry is created."
          }
        ],
        "contextResolution": [
          {
            "targetRef": "TimeLog.workTaskId",
            "source": "selectedEntity",
            "originRef": "WorkTask.workTaskId",
            "description": "The work task currently selected in the UI is resolved from the selected entity context, providing the workTaskId to link the time log to."
          },
          {
            "targetRef": "TimeLog.workerId",
            "source": "actorSession",
            "originRef": "actorSession.actorId",
            "description": "The field worker's identifier is resolved from the authenticated actor session, ensuring the time log is attributed to the logged-in worker."
          },
          {
            "targetRef": "TimeLog.workerRate",
            "source": "actorSession",
            "originRef": "actorSession.actorId",
            "description": "The worker's hourly cost rate is fetched from the platform user profile using the actor session identity, as the module does not maintain its own rate table."
          },
          {
            "targetRef": "TimeLog.timeLogId",
            "source": "systemDefault",
            "originRef": "systemDefault.uuid",
            "description": "A new UUID is generated by the system to serve as the unique identifier for the time log entry."
          },
          {
            "targetRef": "TimeLog.status",
            "source": "systemDefault",
            "originRef": "systemDefault.now",
            "description": "The status is set to posted by default when a new time log is created, indicating the entry is active for job costing."
          },
          {
            "targetRef": "TimeLog.createdAt",
            "source": "systemDefault",
            "originRef": "systemDefault.now",
            "description": "The current timestamp is captured from the system clock at the moment of creation."
          }
        ],
        "accessPattern": {
          "kind": "commandInput",
          "description": "",
          "entity": "TimeLog",
          "keyField": "TimeLog.timeLogId",
          "pagination": "none",
          "selection": "single",
          "output": [
            "TimeLog.timeLogId",
            "TimeLog.workTaskId",
            "TimeLog.workerId",
            "TimeLog.logDate",
            "TimeLog.hours",
            "TimeLog.workerRate",
            "TimeLog.status",
            "TimeLog.createdAt"
          ]
        }
      }
    ],
    "routes": [
      {
        "key": "buildFlowFsm.createTimeLog.createTimeLog",
        "handlerName": "buildFlowFsmCreateTimeLogHandler"
      }
    ]
  }
} as const;

export default createTimeLogController;

export const pipeline = [
  {
    "id": "createTimeLog__httpController",
    "type": "httpController",
    "outputPath": "_102048_/l1/buildFlowFsm/layer_1_external/adapters/http/controllers/createTimeLog.ts",
    "defPath": "_102048_/l1/buildFlowFsm/layer_1_external/adapters/http/controllers/createTimeLog.defs.ts",
    "dependsFiles": [
      "_102048_/l1/buildFlowFsm/layer_2_application/usecases/createTimeLog.d.ts"
    ],
    "dependsOn": [],
    "skills": [
      "_102021_/l2/agentChangeBackend/skills/architecture.md",
      "_102021_/l2/agentChangeBackend/skills/httpController.md",
      "_102034_.d.ts"
    ],
    "agent": "agentCbMaterialize"
  }
] as const;
