/// <mls fileReference="_102048_/l1/buildFlowFsm/layer_1_external/adapters/http/controllers/createChangeOrder.defs.ts" enhancement="_blank"/>

export const createChangeOrderController = {
  "schemaVersion": "2026-06-26",
  "artifactType": "httpController",
  "artifactId": "createChangeOrder",
  "moduleName": "buildFlowFsm",
  "status": "draft",
  "source": {
    "agentName": "agentCbHttpController",
    "stepId": 0,
    "planId": ""
  },
  "data": {
    "pageId": "changeOrderLifecycle",
    "controllerName": "CreateChangeOrderController",
    "ownerKind": "operation",
    "outputSource": "contract",
    "handlers": [
      {
        "handlerName": "buildFlowFsmCreateChangeOrderHandler",
        "command": "createChangeOrder",
        "usecaseRef": "createChangeOrder",
        "inputTypeName": "CreateChangeOrderInput",
        "kind": "create",
        "inputContract": [
          {
            "inputId": "projectId",
            "fieldRef": "ChangeOrder.projectId",
            "required": true,
            "source": "routeParam",
            "description": "The project this change order belongs to, sourced from the current route."
          },
          {
            "inputId": "title",
            "fieldRef": "ChangeOrder.title",
            "required": true,
            "source": "userInput",
            "description": "Short title summarizing the scope change."
          },
          {
            "inputId": "scopeDescription",
            "fieldRef": "ChangeOrder.scopeDescription",
            "required": true,
            "source": "userInput",
            "description": "Detailed description of the scope change being requested."
          },
          {
            "inputId": "amount",
            "fieldRef": "ChangeOrder.amount",
            "required": true,
            "source": "userInput",
            "description": "Cost impact of the change order in USD."
          },
          {
            "inputId": "changeOrderId",
            "fieldRef": "ChangeOrder.changeOrderId",
            "required": true,
            "source": "systemDefault",
            "description": "Generated UUID for the new change order record."
          },
          {
            "inputId": "status",
            "fieldRef": "ChangeOrder.status",
            "required": true,
            "source": "workflowState",
            "description": "Initial lifecycle state set to draft per the changeOrderLifecycle workflow."
          },
          {
            "inputId": "createdAt",
            "fieldRef": "ChangeOrder.createdAt",
            "required": true,
            "source": "systemDefault",
            "description": "Timestamp when the change order record is created."
          },
          {
            "inputId": "updatedAt",
            "fieldRef": "ChangeOrder.updatedAt",
            "required": true,
            "source": "systemDefault",
            "description": "Timestamp of the last modification, set to creation time."
          }
        ],
        "contextResolution": [
          {
            "targetRef": "ChangeOrder.projectId",
            "source": "routeParam",
            "originRef": "routeParam.projectId",
            "description": "Resolved from the current route parameter identifying the project the PM is working within."
          },
          {
            "targetRef": "ChangeOrder.changeOrderId",
            "source": "systemDefault",
            "originRef": "systemDefault.uuid",
            "description": "A new UUID is generated by the backend for the change order record."
          },
          {
            "targetRef": "ChangeOrder.status",
            "source": "workflowState",
            "originRef": "ChangeOrder.status",
            "description": "The initial lifecycle state is set to draft per the changeOrderLifecycle workflow definition."
          },
          {
            "targetRef": "ChangeOrder.createdAt",
            "source": "systemDefault",
            "originRef": "systemDefault.now",
            "description": "The current timestamp is captured at creation time."
          },
          {
            "targetRef": "ChangeOrder.updatedAt",
            "source": "systemDefault",
            "originRef": "systemDefault.now",
            "description": "The current timestamp is captured at creation time, matching createdAt."
          }
        ],
        "accessPattern": {
          "kind": "commandInput",
          "description": "",
          "entity": "ChangeOrder",
          "keyField": "ChangeOrder.changeOrderId",
          "pagination": "none",
          "selection": "none",
          "output": [
            "ChangeOrder.changeOrderId",
            "ChangeOrder.projectId",
            "ChangeOrder.title",
            "ChangeOrder.scopeDescription",
            "ChangeOrder.amount",
            "ChangeOrder.status",
            "ChangeOrder.createdAt"
          ]
        }
      }
    ],
    "routes": [
      {
        "key": "buildFlowFsm.changeOrderLifecycle.createChangeOrder",
        "handlerName": "buildFlowFsmCreateChangeOrderHandler"
      }
    ]
  }
} as const;

export default createChangeOrderController;

export const pipeline = [
  {
    "id": "createChangeOrder__httpController",
    "type": "httpController",
    "outputPath": "_102048_/l1/buildFlowFsm/layer_1_external/adapters/http/controllers/createChangeOrder.ts",
    "defPath": "_102048_/l1/buildFlowFsm/layer_1_external/adapters/http/controllers/createChangeOrder.defs.ts",
    "dependsFiles": [
      "_102048_/l1/buildFlowFsm/layer_2_application/usecases/createChangeOrder.d.ts",
      "_102048_/l2/buildFlowFsm/web/contracts/changeOrderLifecycle.ts"
    ],
    "dependsOn": [],
    "skills": [
      "_102021_/l2/agentChangeBackend/skills/architecture.md",
      "_102021_/l2/agentChangeBackend/skills/httpController.md",
      "_102034_.d.ts"
    ],
    "agent": "agentCbMaterialize"
  }
] as const;
