/// <mls fileReference="_102048_/l1/buildFlowFsm/layer_1_external/adapters/http/controllers/shareStatusReport.defs.ts" enhancement="_blank"/>

export const shareStatusReportController = {
  "schemaVersion": "2026-06-26",
  "artifactType": "httpController",
  "artifactId": "shareStatusReport",
  "moduleName": "buildFlowFsm",
  "status": "draft",
  "source": {
    "agentName": "agentCbHttpController",
    "stepId": 0,
    "planId": ""
  },
  "data": {
    "pageId": "statusReportLifecycle",
    "controllerName": "ShareStatusReportController",
    "ownerKind": "operation",
    "outputSource": "contract",
    "handlers": [
      {
        "handlerName": "buildFlowFsmShareStatusReportHandler",
        "command": "shareStatusReport",
        "usecaseRef": "shareStatusReport",
        "inputTypeName": "ShareStatusReportInput",
        "kind": "update",
        "inputContract": [
          {
            "inputId": "statusReportId",
            "fieldRef": "StatusReport.statusReportId",
            "required": true,
            "source": "selectedEntity",
            "description": "The status report the PM selected to share with the client."
          },
          {
            "inputId": "sharedWithEmail",
            "fieldRef": "StatusReport.sharedWithEmail",
            "required": true,
            "source": "userInput",
            "description": "The client email address the PM enters to send the status report notification."
          },
          {
            "inputId": "actorId",
            "fieldRef": "StatusReport.updatedBy",
            "required": true,
            "source": "actorSession",
            "description": "The project manager performing the share action, resolved from the active session."
          },
          {
            "inputId": "sharedAt",
            "fieldRef": "StatusReport.sharedAt",
            "required": true,
            "source": "systemDefault",
            "description": "Timestamp recording when the report was shared, set to the current server time."
          },
          {
            "inputId": "shareLink",
            "fieldRef": "StatusReport.shareLink",
            "required": true,
            "source": "systemDefault",
            "description": "A unique shareable link generated by the system for client access to the report."
          }
        ],
        "contextResolution": [
          {
            "targetRef": "StatusReport.statusReportId",
            "source": "selectedEntity",
            "originRef": "StatusReport.statusReportId",
            "description": "The single StatusReport selected by the PM on the project detail page, identified by its primary id."
          },
          {
            "targetRef": "StatusReport.updatedBy",
            "source": "actorSession",
            "originRef": "actorSession.actorId",
            "description": "The project manager's actor id resolved from the authenticated session."
          },
          {
            "targetRef": "StatusReport.sharedAt",
            "source": "systemDefault",
            "originRef": "systemDefault.now",
            "description": "The current server timestamp captured at the moment the share command is executed."
          },
          {
            "targetRef": "StatusReport.shareLink",
            "source": "systemDefault",
            "originRef": "systemDefault.uuid",
            "description": "A system-generated unique identifier used to build the shareable link for client access."
          }
        ],
        "accessPattern": {
          "kind": "commandInput",
          "description": "",
          "entity": "StatusReport",
          "keyField": "StatusReport.statusReportId",
          "pagination": "none",
          "selection": "single",
          "output": [
            "StatusReport.status",
            "StatusReport.sharedAt",
            "StatusReport.shareLink",
            "StatusReport.sharedWithEmail"
          ]
        }
      }
    ],
    "routes": [
      {
        "key": "buildFlowFsm.statusReportLifecycle.shareStatusReport",
        "handlerName": "buildFlowFsmShareStatusReportHandler"
      }
    ]
  }
} as const;

export default shareStatusReportController;

export const pipeline = [
  {
    "id": "shareStatusReport__httpController",
    "type": "httpController",
    "outputPath": "_102048_/l1/buildFlowFsm/layer_1_external/adapters/http/controllers/shareStatusReport.ts",
    "defPath": "_102048_/l1/buildFlowFsm/layer_1_external/adapters/http/controllers/shareStatusReport.defs.ts",
    "dependsFiles": [
      "_102048_/l1/buildFlowFsm/layer_2_application/usecases/shareStatusReport.d.ts",
      "_102048_/l2/buildFlowFsm/web/contracts/statusReportLifecycle.ts"
    ],
    "dependsOn": [],
    "skills": [
      "_102021_/l2/agentChangeBackend/skills/architecture.md",
      "_102021_/l2/agentChangeBackend/skills/httpController.md",
      "_102034_.d.ts"
    ],
    "agent": "agentCbMaterialize"
  }
] as const;
