/// <mls fileReference="_102048_/l4/operations/createChangeOrder.defs.ts" enhancement="_blank"/>

export const operationCreateChangeOrder = {
  "operationId": "createChangeOrder",
  "title": "Create a change order",
  "actor": "projectManager",
  "entity": "ChangeOrder",
  "kind": "create",
  "reads": [
    "Project",
    "ChangeOrder"
  ],
  "writes": [
    "ChangeOrder"
  ],
  "rulesApplied": [
    "changeOrderRequiresProject",
    "changeOrderInAppApproval"
  ],
  "story": {
    "actor": "Project Manager",
    "goal": "Document a scope change on a project with its cost impact so it can be sent to the client for in-app approval.",
    "steps": [
      "The project manager opens the change order creation form from a project detail page.",
      "They enter a title, a detailed scope description, and the cost amount for the change.",
      "The system validates the project association and creates the change order in draft status.",
      "The change order is saved and ready to be sent to the client for in-app approval."
    ],
    "outcome": "A new change order record exists in draft status, linked to the project, ready to be sent to the client for approval."
  },
  "accessPattern": {
    "kind": "commandInput",
    "entity": "ChangeOrder",
    "keyField": "ChangeOrder.changeOrderId",
    "pagination": "none",
    "selection": "none",
    "output": [
      "ChangeOrder.changeOrderId",
      "ChangeOrder.projectId",
      "ChangeOrder.title",
      "ChangeOrder.scopeDescription",
      "ChangeOrder.amount",
      "ChangeOrder.status",
      "ChangeOrder.createdAt"
    ]
  },
  "inputs": [
    {
      "inputId": "projectId",
      "fieldRef": "ChangeOrder.projectId",
      "required": true,
      "source": "routeParam",
      "description": "The project this change order belongs to, sourced from the current route."
    },
    {
      "inputId": "title",
      "fieldRef": "ChangeOrder.title",
      "required": true,
      "source": "userInput",
      "description": "Short title summarizing the scope change."
    },
    {
      "inputId": "scopeDescription",
      "fieldRef": "ChangeOrder.scopeDescription",
      "required": true,
      "source": "userInput",
      "description": "Detailed description of the scope change being requested."
    },
    {
      "inputId": "amount",
      "fieldRef": "ChangeOrder.amount",
      "required": true,
      "source": "userInput",
      "description": "Cost impact of the change order in USD."
    },
    {
      "inputId": "changeOrderId",
      "fieldRef": "ChangeOrder.changeOrderId",
      "required": true,
      "source": "systemDefault",
      "description": "Generated UUID for the new change order record."
    },
    {
      "inputId": "status",
      "fieldRef": "ChangeOrder.status",
      "required": true,
      "source": "workflowState",
      "description": "Initial lifecycle state set to draft per the changeOrderLifecycle workflow."
    },
    {
      "inputId": "createdAt",
      "fieldRef": "ChangeOrder.createdAt",
      "required": true,
      "source": "systemDefault",
      "description": "Timestamp when the change order record is created."
    },
    {
      "inputId": "updatedAt",
      "fieldRef": "ChangeOrder.updatedAt",
      "required": true,
      "source": "systemDefault",
      "description": "Timestamp of the last modification, set to creation time."
    }
  ],
  "contextResolution": [
    {
      "targetRef": "ChangeOrder.projectId",
      "source": "routeParam",
      "originRef": "routeParam.projectId",
      "description": "Resolved from the current route parameter identifying the project the PM is working within."
    },
    {
      "targetRef": "ChangeOrder.changeOrderId",
      "source": "systemDefault",
      "originRef": "systemDefault.uuid",
      "description": "A new UUID is generated by the backend for the change order record."
    },
    {
      "targetRef": "ChangeOrder.status",
      "source": "workflowState",
      "originRef": "ChangeOrder.status",
      "description": "The initial lifecycle state is set to draft per the changeOrderLifecycle workflow definition."
    },
    {
      "targetRef": "ChangeOrder.createdAt",
      "source": "systemDefault",
      "originRef": "systemDefault.now",
      "description": "The current timestamp is captured at creation time."
    },
    {
      "targetRef": "ChangeOrder.updatedAt",
      "source": "systemDefault",
      "originRef": "systemDefault.now",
      "description": "The current timestamp is captured at creation time, matching createdAt."
    }
  ],
  "acceptanceAssertions": [
    "After creation, a ChangeOrder record exists with status 'draft'.",
    "The created ChangeOrder is linked to a valid Project via projectId.",
    "The created ChangeOrder has a non-empty title, scopeDescription, and a positive amount.",
    "The created ChangeOrder has changeOrderId, createdAt, and updatedAt populated by the system.",
    "The created ChangeOrder uses in-app approval status workflow and does not require e-signature.",
    "The created ChangeOrder in draft status does not affect job costing or invoicing until it is approved."
  ],
  "pageId": "changeOrderLifecycle",
  "commandName": "createChangeOrder",
  "bffName": "buildFlowFsm.changeOrderLifecycle.createChangeOrder",
  "capability": {
    "capabilityId": "changeOrderLifecycle",
    "title": "Change Order Lifecycle",
    "actor": "projectManager",
    "priority": "now"
  },
  "statusFrontend": "toCreate",
  "statusBackend": "toCreate"
} as const;

export default operationCreateChangeOrder;
