/// <mls fileReference="_102048_/l4/operations/shareStatusReport.defs.ts" enhancement="_blank"/>

export const operationShareStatusReport = {
  "operationId": "shareStatusReport",
  "title": "Share status report with client",
  "actor": "projectManager",
  "entity": "StatusReport",
  "kind": "update",
  "reads": [
    "StatusReport",
    "Project",
    "Client"
  ],
  "writes": [
    "StatusReport"
  ],
  "rulesApplied": [
    "clientSeesPmStatusReport"
  ],
  "story": {
    "actor": "projectManager",
    "goal": "Share a reviewed AI-generated status report with the client so the client has a clear, professional view of project progress.",
    "steps": [
      "The PM selects a status report with status 'generated' from the project detail page.",
      "The PM enters the client email address to receive the report.",
      "The system generates a shareable link and records the share timestamp.",
      "The system transitions the report status from 'generated' to 'shared' and notifies the client via the provided email."
    ],
    "outcome": "The status report is shared with the client at the exact content the PM reviewed, with status 'shared', a share link, and a share timestamp recorded."
  },
  "accessPattern": {
    "kind": "commandInput",
    "entity": "StatusReport",
    "keyField": "StatusReport.statusReportId",
    "pagination": "none",
    "selection": "single",
    "output": [
      "StatusReport.status",
      "StatusReport.sharedAt",
      "StatusReport.shareLink",
      "StatusReport.sharedWithEmail"
    ]
  },
  "inputs": [
    {
      "inputId": "statusReportId",
      "fieldRef": "StatusReport.statusReportId",
      "required": true,
      "source": "selectedEntity",
      "description": "The status report the PM selected to share with the client."
    },
    {
      "inputId": "sharedWithEmail",
      "fieldRef": "StatusReport.sharedWithEmail",
      "required": true,
      "source": "userInput",
      "description": "The client email address the PM enters to send the status report notification."
    },
    {
      "inputId": "actorId",
      "fieldRef": "StatusReport.updatedBy",
      "required": true,
      "source": "actorSession",
      "description": "The project manager performing the share action, resolved from the active session."
    },
    {
      "inputId": "sharedAt",
      "fieldRef": "StatusReport.sharedAt",
      "required": true,
      "source": "systemDefault",
      "description": "Timestamp recording when the report was shared, set to the current server time."
    },
    {
      "inputId": "shareLink",
      "fieldRef": "StatusReport.shareLink",
      "required": true,
      "source": "systemDefault",
      "description": "A unique shareable link generated by the system for client access to the report."
    }
  ],
  "contextResolution": [
    {
      "targetRef": "StatusReport.statusReportId",
      "source": "selectedEntity",
      "originRef": "StatusReport.statusReportId",
      "description": "The single StatusReport selected by the PM on the project detail page, identified by its primary id."
    },
    {
      "targetRef": "StatusReport.updatedBy",
      "source": "actorSession",
      "originRef": "actorSession.actorId",
      "description": "The project manager's actor id resolved from the authenticated session."
    },
    {
      "targetRef": "StatusReport.sharedAt",
      "source": "systemDefault",
      "originRef": "systemDefault.now",
      "description": "The current server timestamp captured at the moment the share command is executed."
    },
    {
      "targetRef": "StatusReport.shareLink",
      "source": "systemDefault",
      "originRef": "systemDefault.uuid",
      "description": "A system-generated unique identifier used to build the shareable link for client access."
    }
  ],
  "acceptanceAssertions": [
    "After sharing, the StatusReport exists with status equal to 'shared'.",
    "After sharing, the StatusReport.sharedAt field is populated with the current timestamp.",
    "After sharing, the StatusReport.shareLink field is populated with a non-empty unique link.",
    "After sharing, the StatusReport.sharedWithEmail field matches the email address provided by the PM.",
    "The report content visible to the client is identical to the content the PM reviewed — no separate or modified report is produced.",
    "The operation fails if the selected StatusReport does not have status 'generated'."
  ],
  "pageId": "statusReportLifecycle",
  "commandName": "shareStatusReport",
  "bffName": "buildFlowFsm.statusReportLifecycle.shareStatusReport",
  "capability": {
    "capabilityId": "statusReportLifecycle",
    "title": "Status Report Lifecycle",
    "actor": "projectManager",
    "priority": "now"
  },
  "statusFrontend": "toCreate",
  "statusBackend": "toCreate"
} as const;

export default operationShareStatusReport;
