/// <mls fileReference="_102048_/l2/buildFlowFsm/web/desktop/page11/statusReportLifecycle.defs.ts" enhancement="_blank"/>

export const definition = {
  "pageId": "statusReportLifecycle",
  "pageName": "AI Status Report",
  "baseClassName": "BuildFlowFsmStatusReportLifecycleBase",
  "actor": "projectManager",
  "purpose": "Executar AI Status Report.",
  "capabilities": [
    "statusReportLifecycle"
  ],
  "flowRefs": {
    "experienceFlows": [
      "statusReportLifecycle"
    ],
    "entityLifecycles": [],
    "taskWorkflows": [
      "statusReportLifecycle"
    ],
    "automations": []
  },
  "pluginRefs": [],
  "mdmRefs": [],
  "origin": {
    "source": "l4-journey",
    "workspaceId": "statusReportLifecycle",
    "workspaceKind": "workflow",
    "workflowId": "statusReportLifecycle",
    "actor": "projectManager",
    "entity": "StatusReport",
    "owners": [
      {
        "kind": "workflow",
        "id": "statusReportLifecycle",
        "defPath": "_102048_/l4/workflows/statusReportLifecycle.defs.ts"
      },
      {
        "kind": "operation",
        "id": "generateStatusReport",
        "defPath": "_102048_/l4/operations/generateStatusReport.defs.ts"
      },
      {
        "kind": "operation",
        "id": "shareStatusReport",
        "defPath": "_102048_/l4/operations/shareStatusReport.defs.ts"
      }
    ],
    "microUserFlow": {
      "source": "l4/story.steps",
      "workflowSteps": [
        "The project manager clicks 'Generate Status Report' on the project detail page so the system compiles tasks, time logs, and material usage into a professional summary using the LLM proxy.",
        "The project manager reviews the generated report to make sure it accurately reflects project progress, costs, and any delay risks before sharing it with the client.",
        "The project manager shares the status report with the client via a shareable link or email so the client has a clear, professional view of where the project stands."
      ],
      "operations": [
        {
          "operationId": "generateStatusReport",
          "commandName": "generateStatusReport",
          "steps": [
            "The PM opens the project detail page and clicks 'Generate Status Report', specifying the reporting period start and end dates.",
            "The backend reads WorkTask, TimeLog, and MaterialUsage records for the project within the specified period.",
            "The platform LLM proxy compiles the data into a plain-language status report covering progress, costs, and delay risks.",
            "A new StatusReport record is created with status 'generated', the AI-produced content, and the reporting period dates."
          ]
        },
        {
          "operationId": "shareStatusReport",
          "commandName": "shareStatusReport",
          "steps": [
            "The PM selects a status report with status 'generated' from the project detail page.",
            "The PM enters the client email address to receive the report.",
            "The system generates a shareable link and records the share timestamp.",
            "The system transitions the report status from 'generated' to 'shared' and notifies the client via the provided email."
          ]
        }
      ]
    }
  },
  "pageInputs": [],
  "navigationRefs": [],
  "sections": [
    {
      "id": "sec_generate",
      "type": "section",
      "sectionName": "Generate Status Report",
      "titleKey": "section.generate.title",
      "mode": "edit",
      "order": 10,
      "organisms": [
        {
          "id": "org_generate",
          "type": "organism",
          "organismName": "GenerateStatusReport",
          "titleKey": "org.generate.title",
          "purpose": "Generate AI status report",
          "userActions": [
            "generateStatusReport"
          ],
          "requiredEntities": [
            "StatusReport",
            "Project",
            "WorkTask",
            "TimeLog",
            "MaterialUsage"
          ],
          "readsFields": [
            "projectId"
          ],
          "writesFields": [
            "reportPeriodStart",
            "reportPeriodEnd",
            "statusReportId",
            "status",
            "content",
            "generatedAt",
            "llmModelUsed",
            "createdAt"
          ],
          "rulesApplied": [
            "statusReportAutoGenerated",
            "llmProxyUsage"
          ],
          "order": 10,
          "intentionRefs": [
            {
              "id": "intent_generate_form",
              "intent": "commandForm",
              "stateKey": "ui.statusReportLifecycle.action.generateStatusReport.status",
              "action": "generateStatusReport",
              "submitAction": "generateStatusReport",
              "order": 10
            },
            {
              "id": "intent_workflow_status",
              "intent": "workflowStatus",
              "stateKey": "ui.statusReportLifecycle.status",
              "order": 20
            }
          ]
        }
      ]
    },
    {
      "id": "sec_review",
      "type": "section",
      "sectionName": "Review Generated Report",
      "titleKey": "section.review.title",
      "mode": "view",
      "order": 20,
      "organisms": [
        {
          "id": "org_review",
          "type": "organism",
          "organismName": "ReviewStatusReport",
          "titleKey": "org.review.title",
          "purpose": "Review the AI-generated status report before sharing with the client",
          "userActions": [],
          "requiredEntities": [
            "StatusReport",
            "Project"
          ],
          "readsFields": [
            "statusReportId",
            "content",
            "reportPeriodStart",
            "reportPeriodEnd",
            "status",
            "generatedAt",
            "llmModelUsed",
            "createdAt"
          ],
          "writesFields": [],
          "rulesApplied": [
            "statusReportAutoGenerated",
            "llmProxyUsage"
          ],
          "order": 10,
          "intentionRefs": [
            {
              "id": "intent_review_summary",
              "intent": "summary",
              "order": 10
            }
          ]
        }
      ]
    },
    {
      "id": "sec_share",
      "type": "section",
      "sectionName": "Share Status Report",
      "titleKey": "section.share.title",
      "mode": "edit",
      "order": 30,
      "organisms": [
        {
          "id": "org_share",
          "type": "organism",
          "organismName": "ShareStatusReport",
          "titleKey": "org.share.title",
          "purpose": "Share status report with client via email",
          "userActions": [
            "shareStatusReport"
          ],
          "requiredEntities": [
            "StatusReport",
            "Project",
            "Client"
          ],
          "readsFields": [
            "statusReportId",
            "status"
          ],
          "writesFields": [
            "status",
            "sharedAt",
            "shareLink",
            "sharedWithEmail"
          ],
          "rulesApplied": [
            "clientSeesPmStatusReport"
          ],
          "order": 10,
          "intentionRefs": [
            {
              "id": "intent_share_form",
              "intent": "commandForm",
              "stateKey": "ui.statusReportLifecycle.action.shareStatusReport.status",
              "action": "shareStatusReport",
              "submitAction": "shareStatusReport",
              "order": 10
            },
            {
              "id": "intent_share_result",
              "intent": "summary",
              "order": 20
            }
          ]
        }
      ]
    }
  ],
  "layout": {
    "id": "wizard_flow_page11",
    "type": "page",
    "sections": [
      {
        "id": "sec_generate",
        "type": "section",
        "sectionName": "Generate Status Report",
        "titleKey": "section.generate.title",
        "mode": "edit",
        "order": 10,
        "organisms": [
          {
            "id": "org_generate",
            "type": "organism",
            "organismName": "GenerateStatusReport",
            "titleKey": "org.generate.title",
            "purpose": "Generate AI status report",
            "userActions": [
              "generateStatusReport"
            ],
            "requiredEntities": [
              "StatusReport",
              "Project",
              "WorkTask",
              "TimeLog",
              "MaterialUsage"
            ],
            "readsFields": [
              "projectId"
            ],
            "writesFields": [
              "reportPeriodStart",
              "reportPeriodEnd",
              "statusReportId",
              "status",
              "content",
              "generatedAt",
              "llmModelUsed",
              "createdAt"
            ],
            "rulesApplied": [
              "statusReportAutoGenerated",
              "llmProxyUsage"
            ],
            "order": 10,
            "intentions": [
              {
                "id": "intent_generate_form",
                "intent": "commandForm",
                "order": 10,
                "titleKey": "intention.generate.title",
                "action": "generateStatusReport",
                "submitAction": "generateStatusReport",
                "displayHint": "form",
                "stateKey": "ui.statusReportLifecycle.action.generateStatusReport.status",
                "fields": [
                  {
                    "id": "fld_projectId",
                    "field": "projectId",
                    "labelKey": "field.projectId.label",
                    "order": 10,
                    "required": true,
                    "inputType": "hidden",
                    "source": "routeParam",
                    "stateKey": "ui.statusReportLifecycle.input.generateStatusReport.projectId"
                  },
                  {
                    "id": "fld_reportPeriodStart",
                    "field": "reportPeriodStart",
                    "labelKey": "field.reportPeriodStart.label",
                    "order": 20,
                    "required": true,
                    "inputType": "date",
                    "source": "userInput",
                    "stateKey": "ui.statusReportLifecycle.input.generateStatusReport.reportPeriodStart"
                  },
                  {
                    "id": "fld_reportPeriodEnd",
                    "field": "reportPeriodEnd",
                    "labelKey": "field.reportPeriodEnd.label",
                    "order": 30,
                    "required": true,
                    "inputType": "date",
                    "source": "userInput",
                    "stateKey": "ui.statusReportLifecycle.input.generateStatusReport.reportPeriodEnd"
                  }
                ],
                "columns": [],
                "filters": [],
                "toolbar": [],
                "rowActions": [],
                "actions": [
                  {
                    "id": "act_generate",
                    "action": "generateStatusReport",
                    "labelKey": "action.generateStatusReport.label",
                    "order": 10,
                    "displayHint": "primary",
                    "actionKey": "generateStatusReport"
                  }
                ]
              },
              {
                "id": "intent_workflow_status",
                "intent": "workflowStatus",
                "order": 20,
                "titleKey": "intention.workflowStatus.title",
                "displayHint": "status-badge",
                "stateKey": "ui.statusReportLifecycle.status",
                "fields": [
                  {
                    "id": "fld_wf_status",
                    "field": "status",
                    "labelKey": "field.status.label",
                    "order": 10,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system",
                    "stateKey": "ui.statusReportLifecycle.layout.fld_wf_status"
                  }
                ],
                "columns": [],
                "filters": [],
                "toolbar": [],
                "rowActions": [],
                "actions": []
              }
            ]
          }
        ]
      },
      {
        "id": "sec_review",
        "type": "section",
        "sectionName": "Review Generated Report",
        "titleKey": "section.review.title",
        "mode": "view",
        "order": 20,
        "organisms": [
          {
            "id": "org_review",
            "type": "organism",
            "organismName": "ReviewStatusReport",
            "titleKey": "org.review.title",
            "purpose": "Review the AI-generated status report before sharing with the client",
            "userActions": [],
            "requiredEntities": [
              "StatusReport",
              "Project"
            ],
            "readsFields": [
              "statusReportId",
              "content",
              "reportPeriodStart",
              "reportPeriodEnd",
              "status",
              "generatedAt",
              "llmModelUsed",
              "createdAt"
            ],
            "writesFields": [],
            "rulesApplied": [
              "statusReportAutoGenerated",
              "llmProxyUsage"
            ],
            "order": 10,
            "intentions": [
              {
                "id": "intent_review_summary",
                "intent": "summary",
                "order": 10,
                "titleKey": "intention.review.title",
                "emptyKey": "empty.review",
                "displayHint": "report-preview",
                "fields": [
                  {
                    "id": "fld_review_statusReportId",
                    "field": "statusReportId",
                    "labelKey": "field.statusReportId.label",
                    "order": 10,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system"
                  },
                  {
                    "id": "fld_review_content",
                    "field": "content",
                    "labelKey": "field.content.label",
                    "order": 20,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system"
                  },
                  {
                    "id": "fld_review_periodStart",
                    "field": "reportPeriodStart",
                    "labelKey": "field.reportPeriodStart.label",
                    "order": 30,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system"
                  },
                  {
                    "id": "fld_review_periodEnd",
                    "field": "reportPeriodEnd",
                    "labelKey": "field.reportPeriodEnd.label",
                    "order": 40,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system"
                  },
                  {
                    "id": "fld_review_status",
                    "field": "status",
                    "labelKey": "field.status.label",
                    "order": 50,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system",
                    "stateKey": "ui.statusReportLifecycle.status"
                  },
                  {
                    "id": "fld_review_generatedAt",
                    "field": "generatedAt",
                    "labelKey": "field.generatedAt.label",
                    "order": 60,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system"
                  },
                  {
                    "id": "fld_review_llmModel",
                    "field": "llmModelUsed",
                    "labelKey": "field.llmModelUsed.label",
                    "order": 70,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system"
                  },
                  {
                    "id": "fld_review_createdAt",
                    "field": "createdAt",
                    "labelKey": "field.createdAt.label",
                    "order": 80,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system"
                  }
                ],
                "columns": [],
                "filters": [],
                "toolbar": [],
                "rowActions": [],
                "actions": []
              }
            ]
          }
        ]
      },
      {
        "id": "sec_share",
        "type": "section",
        "sectionName": "Share Status Report",
        "titleKey": "section.share.title",
        "mode": "edit",
        "order": 30,
        "organisms": [
          {
            "id": "org_share",
            "type": "organism",
            "organismName": "ShareStatusReport",
            "titleKey": "org.share.title",
            "purpose": "Share status report with client via email",
            "userActions": [
              "shareStatusReport"
            ],
            "requiredEntities": [
              "StatusReport",
              "Project",
              "Client"
            ],
            "readsFields": [
              "statusReportId",
              "status"
            ],
            "writesFields": [
              "status",
              "sharedAt",
              "shareLink",
              "sharedWithEmail"
            ],
            "rulesApplied": [
              "clientSeesPmStatusReport"
            ],
            "order": 10,
            "intentions": [
              {
                "id": "intent_share_form",
                "intent": "commandForm",
                "order": 10,
                "titleKey": "intention.share.title",
                "action": "shareStatusReport",
                "submitAction": "shareStatusReport",
                "displayHint": "form",
                "stateKey": "ui.statusReportLifecycle.action.shareStatusReport.status",
                "fields": [
                  {
                    "id": "fld_share_statusReportId",
                    "field": "statusReportId",
                    "labelKey": "field.statusReportId.label",
                    "order": 10,
                    "required": true,
                    "inputType": "hidden",
                    "source": "selectedEntity",
                    "stateKey": "ui.statusReportLifecycle.input.shareStatusReport.statusReportId"
                  },
                  {
                    "id": "fld_share_email",
                    "field": "sharedWithEmail",
                    "labelKey": "field.sharedWithEmail.label",
                    "order": 20,
                    "required": true,
                    "inputType": "email",
                    "source": "userInput",
                    "stateKey": "ui.statusReportLifecycle.input.shareStatusReport.sharedWithEmail"
                  }
                ],
                "columns": [],
                "filters": [],
                "toolbar": [],
                "rowActions": [],
                "actions": [
                  {
                    "id": "act_share",
                    "action": "shareStatusReport",
                    "labelKey": "action.shareStatusReport.label",
                    "order": 10,
                    "displayHint": "primary",
                    "actionKey": "shareStatusReport"
                  }
                ]
              },
              {
                "id": "intent_share_result",
                "intent": "summary",
                "order": 20,
                "titleKey": "intention.shareResult.title",
                "emptyKey": "empty.shareResult",
                "displayHint": "share-confirmation",
                "fields": [
                  {
                    "id": "fld_result_status",
                    "field": "status",
                    "labelKey": "field.status.label",
                    "order": 10,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system",
                    "stateKey": "ui.statusReportLifecycle.layout.fld_result_status"
                  },
                  {
                    "id": "fld_result_sharedAt",
                    "field": "sharedAt",
                    "labelKey": "field.sharedAt.label",
                    "order": 20,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system",
                    "stateKey": "ui.statusReportLifecycle.layout.fld_result_sharedAt"
                  },
                  {
                    "id": "fld_result_shareLink",
                    "field": "shareLink",
                    "labelKey": "field.shareLink.label",
                    "order": 30,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system",
                    "stateKey": "ui.statusReportLifecycle.layout.fld_result_shareLink"
                  },
                  {
                    "id": "fld_result_email",
                    "field": "sharedWithEmail",
                    "labelKey": "field.sharedWithEmail.label",
                    "order": 40,
                    "required": false,
                    "inputType": "readonly",
                    "source": "system",
                    "stateKey": "ui.statusReportLifecycle.input.shareStatusReport.sharedWithEmail"
                  }
                ],
                "columns": [],
                "filters": [],
                "toolbar": [],
                "rowActions": [],
                "actions": []
              }
            ]
          }
        ]
      }
    ]
  },
  "dataBindings": [
    {
      "id": "binding_generateStatusReport",
      "source": "buildFlowFsm.statusReportLifecycle.generateStatusReport",
      "entity": "StatusReport",
      "command": "generateStatusReport",
      "description": "Generates an AI status report from project tasks, time logs, and material usage within the specified reporting period.",
      "stateKey": "ui.statusReportLifecycle.output.generateStatusReport",
      "inputStateKeys": [
        "ui.statusReportLifecycle.input.generateStatusReport.projectId",
        "ui.statusReportLifecycle.input.generateStatusReport.reportPeriodStart",
        "ui.statusReportLifecycle.input.generateStatusReport.reportPeriodEnd"
      ]
    },
    {
      "id": "binding_shareStatusReport",
      "source": "buildFlowFsm.statusReportLifecycle.shareStatusReport",
      "entity": "StatusReport",
      "command": "shareStatusReport",
      "description": "Shares a generated status report with the client via email and transitions the report status to shared.",
      "stateKey": "ui.statusReportLifecycle.output.shareStatusReport",
      "inputStateKeys": [
        "ui.statusReportLifecycle.input.shareStatusReport.statusReportId",
        "ui.statusReportLifecycle.input.shareStatusReport.sharedWithEmail"
      ]
    }
  ]
};

export const pipeline = [
  {
    "id": "statusReportLifecycle__l2_page",
    "type": "l2_page",
    "outputPath": "_102048_/l2/buildFlowFsm/web/desktop/page11/statusReportLifecycle.ts",
    "defPath": "_102048_/l2/buildFlowFsm/web/desktop/page11/statusReportLifecycle.defs.ts",
    "dependsFiles": [
      "_102048_/l2/buildFlowFsm/web/shared/statusReportLifecycle.defs.ts",
      "_102048_/l2/buildFlowFsm/web/shared/statusReportLifecycle.ts",
      "_102048_/l2/buildFlowFsm/web/contracts/statusReportLifecycle.defs.ts",
      "_102048_/l2/buildFlowFsm/web/contracts/statusReportLifecycle.ts",
      "_102048_/l2/designSystem.ts"
    ],
    "dependsOn": [
      "statusReportLifecycle__l2_shared"
    ],
    "skills": [
      "_102020_/l2/agentChangeFrontend/skills/genCfePage11RenderTs.ts"
    ],
    "visualStyle": {
      "description": "Dashboard-first, data-dense, status-driven UI with timeline views, cost tracking panels, and mobile-friendly field logging"
    },
    "agent": "agentCfeMaterializeGen"
  }
] as const;
