/// <mls fileReference="_102048_/l2/buildFlowFsm/web/shared/projectManagement.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { BuildFlowFsmProjectManagementBase } from './projectManagement.js';
import type { BuildFlowFsmCreateProjectInput, BuildFlowFsmUpdateProjectInput, BuildFlowFsmUpdateProjectStatusInput, BuildFlowFsmViewDashboardOutput, BuildFlowFsmViewProjectInput, BuildFlowFsmViewProjectOutput } from '../contracts/projectManagement.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: BuildFlowFsmProjectManagementBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_createProjectState = Assert<Assignable<typeof page.createProjectState, "idle" | "loading" | "success" | "error">>;
type _State_createProjectName = Assert<Assignable<typeof page.createProjectName, string | BuildFlowFsmCreateProjectInput["name"]>>;
type _State_createProjectClientId = Assert<Assignable<typeof page.createProjectClientId, string | BuildFlowFsmCreateProjectInput["clientId"]>>;
type _State_createProjectSiteAddress = Assert<Assignable<typeof page.createProjectSiteAddress, string | BuildFlowFsmCreateProjectInput["siteAddress"]>>;
type _State_createProjectBudget = Assert<Assignable<typeof page.createProjectBudget, string | BuildFlowFsmCreateProjectInput["budget"]>>;
type _State_createProjectStartDate = Assert<Assignable<typeof page.createProjectStartDate, string | BuildFlowFsmCreateProjectInput["startDate"]>>;
type _State_createProjectEndDate = Assert<Assignable<typeof page.createProjectEndDate, string | BuildFlowFsmCreateProjectInput["endDate"]>>;
type _State_createProjectStatus = Assert<Assignable<typeof page.createProjectStatus, string | BuildFlowFsmCreateProjectInput["status"]>>;
type _State_updateProjectStatusState = Assert<Assignable<typeof page.updateProjectStatusState, "idle" | "loading" | "success" | "error">>;
type _State_updateProjectStatusProjectId = Assert<Assignable<typeof page.updateProjectStatusProjectId, string | BuildFlowFsmUpdateProjectStatusInput["projectId"]>>;
type _State_updateProjectStatusStatus = Assert<Assignable<typeof page.updateProjectStatusStatus, string | BuildFlowFsmUpdateProjectStatusInput["status"]>>;
type _State_updateProjectStatusCancellationReason = Assert<Assignable<typeof page.updateProjectStatusCancellationReason, string | BuildFlowFsmUpdateProjectStatusInput["cancellationReason"]>>;
type _State_updateProjectState = Assert<Assignable<typeof page.updateProjectState, "idle" | "loading" | "success" | "error">>;
type _State_updateProjectProjectId = Assert<Assignable<typeof page.updateProjectProjectId, string | BuildFlowFsmUpdateProjectInput["projectId"]>>;
type _State_updateProjectName = Assert<Assignable<typeof page.updateProjectName, string | BuildFlowFsmUpdateProjectInput["name"]>>;
type _State_updateProjectClientId = Assert<Assignable<typeof page.updateProjectClientId, string | BuildFlowFsmUpdateProjectInput["clientId"]>>;
type _State_updateProjectSiteAddress = Assert<Assignable<typeof page.updateProjectSiteAddress, string | BuildFlowFsmUpdateProjectInput["siteAddress"]>>;
type _State_updateProjectBudget = Assert<Assignable<typeof page.updateProjectBudget, string | BuildFlowFsmUpdateProjectInput["budget"]>>;
type _State_updateProjectStartDate = Assert<Assignable<typeof page.updateProjectStartDate, string | BuildFlowFsmUpdateProjectInput["startDate"]>>;
type _State_updateProjectEndDate = Assert<Assignable<typeof page.updateProjectEndDate, string | BuildFlowFsmUpdateProjectInput["endDate"]>>;
type _State_viewProjectState = Assert<Assignable<typeof page.viewProjectState, "idle" | "loading" | "success" | "error">>;
type _State_viewProjectProjectId = Assert<Assignable<typeof page.viewProjectProjectId, string | BuildFlowFsmViewProjectInput["projectId"]>>;
type _State_viewProjectData = Assert<Assignable<typeof page.viewProjectData, BuildFlowFsmViewProjectOutput | null>>;
type _State_viewDashboardState = Assert<Assignable<typeof page.viewDashboardState, "idle" | "loading" | "success" | "error">>;
type _State_viewDashboardData = Assert<Assignable<typeof page.viewDashboardData, BuildFlowFsmViewDashboardOutput>>;
type _State_activeCompanyId = Assert<Assignable<typeof page.activeCompanyId, string>>;
type _State_OutputCreateProject = Assert<Assignable<typeof page.OutputCreateProject, unknown>>;
type _State_OutputUpdateProjectStatus = Assert<Assignable<typeof page.OutputUpdateProjectStatus, unknown>>;
type _State_OutputUpdateProject = Assert<Assignable<typeof page.OutputUpdateProject, unknown>>;
type _State_LayoutFldActiveCompanyId = Assert<Assignable<typeof page.LayoutFldActiveCompanyId, string>>;
type _Action_createProject = Assert<Assignable<typeof page.createProject, (...args: any[]) => unknown>>;
type _Handler_handleCreateProjectClick = Assert<Assignable<typeof page.handleCreateProjectClick, (...args: any[]) => unknown>>;
type _Action_updateProjectStatus = Assert<Assignable<typeof page.updateProjectStatus, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectStatusClick = Assert<Assignable<typeof page.handleUpdateProjectStatusClick, (...args: any[]) => unknown>>;
type _Action_updateProject = Assert<Assignable<typeof page.updateProject, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectClick = Assert<Assignable<typeof page.handleUpdateProjectClick, (...args: any[]) => unknown>>;
type _Action_loadViewProject = Assert<Assignable<typeof page.loadViewProject, (...args: any[]) => unknown>>;
type _Handler_handleViewProjectClick = Assert<Assignable<typeof page.handleViewProjectClick, (...args: any[]) => unknown>>;
type _Action_loadViewDashboard = Assert<Assignable<typeof page.loadViewDashboard, (...args: any[]) => unknown>>;
type _Handler_handleViewDashboardClick = Assert<Assignable<typeof page.handleViewDashboardClick, (...args: any[]) => unknown>>;
type _Action_setCreateProjectName = Assert<Assignable<typeof page.setCreateProjectName, (...args: any[]) => unknown>>;
type _Handler_handleCreateProjectNameChange = Assert<Assignable<typeof page.handleCreateProjectNameChange, (...args: any[]) => unknown>>;
type _Action_setCreateProjectClientId = Assert<Assignable<typeof page.setCreateProjectClientId, (...args: any[]) => unknown>>;
type _Handler_handleCreateProjectClientIdChange = Assert<Assignable<typeof page.handleCreateProjectClientIdChange, (...args: any[]) => unknown>>;
type _Action_setCreateProjectSiteAddress = Assert<Assignable<typeof page.setCreateProjectSiteAddress, (...args: any[]) => unknown>>;
type _Handler_handleCreateProjectSiteAddressChange = Assert<Assignable<typeof page.handleCreateProjectSiteAddressChange, (...args: any[]) => unknown>>;
type _Action_setCreateProjectBudget = Assert<Assignable<typeof page.setCreateProjectBudget, (...args: any[]) => unknown>>;
type _Handler_handleCreateProjectBudgetChange = Assert<Assignable<typeof page.handleCreateProjectBudgetChange, (...args: any[]) => unknown>>;
type _Action_setCreateProjectStartDate = Assert<Assignable<typeof page.setCreateProjectStartDate, (...args: any[]) => unknown>>;
type _Handler_handleCreateProjectStartDateChange = Assert<Assignable<typeof page.handleCreateProjectStartDateChange, (...args: any[]) => unknown>>;
type _Action_setCreateProjectEndDate = Assert<Assignable<typeof page.setCreateProjectEndDate, (...args: any[]) => unknown>>;
type _Handler_handleCreateProjectEndDateChange = Assert<Assignable<typeof page.handleCreateProjectEndDateChange, (...args: any[]) => unknown>>;
type _Action_setCreateProjectStatus = Assert<Assignable<typeof page.setCreateProjectStatus, (...args: any[]) => unknown>>;
type _Handler_handleCreateProjectStatusChange = Assert<Assignable<typeof page.handleCreateProjectStatusChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProjectStatusProjectId = Assert<Assignable<typeof page.setUpdateProjectStatusProjectId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectStatusProjectIdChange = Assert<Assignable<typeof page.handleUpdateProjectStatusProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProjectStatusStatus = Assert<Assignable<typeof page.setUpdateProjectStatusStatus, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectStatusStatusChange = Assert<Assignable<typeof page.handleUpdateProjectStatusStatusChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProjectStatusCancellationReason = Assert<Assignable<typeof page.setUpdateProjectStatusCancellationReason, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectStatusCancellationReasonChange = Assert<Assignable<typeof page.handleUpdateProjectStatusCancellationReasonChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProjectProjectId = Assert<Assignable<typeof page.setUpdateProjectProjectId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectProjectIdChange = Assert<Assignable<typeof page.handleUpdateProjectProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProjectName = Assert<Assignable<typeof page.setUpdateProjectName, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectNameChange = Assert<Assignable<typeof page.handleUpdateProjectNameChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProjectClientId = Assert<Assignable<typeof page.setUpdateProjectClientId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectClientIdChange = Assert<Assignable<typeof page.handleUpdateProjectClientIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProjectSiteAddress = Assert<Assignable<typeof page.setUpdateProjectSiteAddress, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectSiteAddressChange = Assert<Assignable<typeof page.handleUpdateProjectSiteAddressChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProjectBudget = Assert<Assignable<typeof page.setUpdateProjectBudget, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectBudgetChange = Assert<Assignable<typeof page.handleUpdateProjectBudgetChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProjectStartDate = Assert<Assignable<typeof page.setUpdateProjectStartDate, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectStartDateChange = Assert<Assignable<typeof page.handleUpdateProjectStartDateChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProjectEndDate = Assert<Assignable<typeof page.setUpdateProjectEndDate, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProjectEndDateChange = Assert<Assignable<typeof page.handleUpdateProjectEndDateChange, (...args: any[]) => unknown>>;
type _Action_setViewProjectProjectId = Assert<Assignable<typeof page.setViewProjectProjectId, (...args: any[]) => unknown>>;
type _Handler_handleViewProjectProjectIdChange = Assert<Assignable<typeof page.handleViewProjectProjectIdChange, (...args: any[]) => unknown>>;

export {};