/// <mls fileReference="_102048_/l2/buildFlowFsm/web/shared/workTaskLifecycle.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { BuildFlowFsmWorkTaskLifecycleBase } from './workTaskLifecycle.js';
import type { BuildFlowFsmAssignTaskInput, BuildFlowFsmCreateTaskInput, BuildFlowFsmUpdateTaskInput } from '../contracts/workTaskLifecycle.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: BuildFlowFsmWorkTaskLifecycleBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_createTaskState = Assert<Assignable<typeof page.createTaskState, "idle" | "loading" | "success" | "error">>;
type _State_createTaskTitle = Assert<Assignable<typeof page.createTaskTitle, string | BuildFlowFsmCreateTaskInput["title"]>>;
type _State_createTaskDescription = Assert<Assignable<typeof page.createTaskDescription, string | BuildFlowFsmCreateTaskInput["description"]>>;
type _State_createTaskDueDate = Assert<Assignable<typeof page.createTaskDueDate, string | BuildFlowFsmCreateTaskInput["dueDate"]>>;
type _State_createTaskAssignedWorkerId = Assert<Assignable<typeof page.createTaskAssignedWorkerId, string | BuildFlowFsmCreateTaskInput["assignedWorkerId"]>>;
type _State_createTaskAssignedWorkerName = Assert<Assignable<typeof page.createTaskAssignedWorkerName, string | BuildFlowFsmCreateTaskInput["assignedWorkerName"]>>;
type _State_createTaskBudgetedCost = Assert<Assignable<typeof page.createTaskBudgetedCost, string | BuildFlowFsmCreateTaskInput["budgetedCost"]>>;
type _State_createTaskSequenceNumber = Assert<Assignable<typeof page.createTaskSequenceNumber, string | BuildFlowFsmCreateTaskInput["sequenceNumber"]>>;
type _State_createTaskProjectId = Assert<Assignable<typeof page.createTaskProjectId, string | BuildFlowFsmCreateTaskInput["projectId"]>>;
type _State_assignTaskState = Assert<Assignable<typeof page.assignTaskState, "idle" | "loading" | "success" | "error">>;
type _State_assignTaskWorkTaskId = Assert<Assignable<typeof page.assignTaskWorkTaskId, string | BuildFlowFsmAssignTaskInput["workTaskId"]>>;
type _State_assignTaskAssignedWorkerId = Assert<Assignable<typeof page.assignTaskAssignedWorkerId, string | BuildFlowFsmAssignTaskInput["assignedWorkerId"]>>;
type _State_assignTaskAssignedWorkerName = Assert<Assignable<typeof page.assignTaskAssignedWorkerName, string | BuildFlowFsmAssignTaskInput["assignedWorkerName"]>>;
type _State_assignTaskDueDate = Assert<Assignable<typeof page.assignTaskDueDate, string | BuildFlowFsmAssignTaskInput["dueDate"]>>;
type _State_updateTaskState = Assert<Assignable<typeof page.updateTaskState, "idle" | "loading" | "success" | "error">>;
type _State_updateTaskWorkTaskId = Assert<Assignable<typeof page.updateTaskWorkTaskId, string | BuildFlowFsmUpdateTaskInput["workTaskId"]>>;
type _State_updateTaskProjectId = Assert<Assignable<typeof page.updateTaskProjectId, string | BuildFlowFsmUpdateTaskInput["projectId"]>>;
type _State_updateTaskTitle = Assert<Assignable<typeof page.updateTaskTitle, string | BuildFlowFsmUpdateTaskInput["title"]>>;
type _State_updateTaskDescription = Assert<Assignable<typeof page.updateTaskDescription, string | BuildFlowFsmUpdateTaskInput["description"]>>;
type _State_updateTaskAssignedWorkerId = Assert<Assignable<typeof page.updateTaskAssignedWorkerId, string | BuildFlowFsmUpdateTaskInput["assignedWorkerId"]>>;
type _State_updateTaskAssignedWorkerName = Assert<Assignable<typeof page.updateTaskAssignedWorkerName, string | BuildFlowFsmUpdateTaskInput["assignedWorkerName"]>>;
type _State_updateTaskDueDate = Assert<Assignable<typeof page.updateTaskDueDate, string | BuildFlowFsmUpdateTaskInput["dueDate"]>>;
type _State_updateTaskBudgetedCost = Assert<Assignable<typeof page.updateTaskBudgetedCost, string | BuildFlowFsmUpdateTaskInput["budgetedCost"]>>;
type _State_updateTaskSequenceNumber = Assert<Assignable<typeof page.updateTaskSequenceNumber, string | BuildFlowFsmUpdateTaskInput["sequenceNumber"]>>;
type _State_OutputCreateTask = Assert<Assignable<typeof page.OutputCreateTask, unknown>>;
type _State_OutputAssignTask = Assert<Assignable<typeof page.OutputAssignTask, unknown>>;
type _State_OutputUpdateTask = Assert<Assignable<typeof page.OutputUpdateTask, unknown>>;
type _Action_createTask = Assert<Assignable<typeof page.createTask, (...args: any[]) => unknown>>;
type _Handler_handleCreateTaskClick = Assert<Assignable<typeof page.handleCreateTaskClick, (...args: any[]) => unknown>>;
type _Action_assignTask = Assert<Assignable<typeof page.assignTask, (...args: any[]) => unknown>>;
type _Handler_handleAssignTaskClick = Assert<Assignable<typeof page.handleAssignTaskClick, (...args: any[]) => unknown>>;
type _Action_updateTask = Assert<Assignable<typeof page.updateTask, (...args: any[]) => unknown>>;
type _Handler_handleUpdateTaskClick = Assert<Assignable<typeof page.handleUpdateTaskClick, (...args: any[]) => unknown>>;
type _Action_setCreateTaskTitle = Assert<Assignable<typeof page.setCreateTaskTitle, (...args: any[]) => unknown>>;
type _Handler_handleCreateTaskTitleChange = Assert<Assignable<typeof page.handleCreateTaskTitleChange, (...args: any[]) => unknown>>;
type _Action_setCreateTaskDescription = Assert<Assignable<typeof page.setCreateTaskDescription, (...args: any[]) => unknown>>;
type _Handler_handleCreateTaskDescriptionChange = Assert<Assignable<typeof page.handleCreateTaskDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCreateTaskDueDate = Assert<Assignable<typeof page.setCreateTaskDueDate, (...args: any[]) => unknown>>;
type _Handler_handleCreateTaskDueDateChange = Assert<Assignable<typeof page.handleCreateTaskDueDateChange, (...args: any[]) => unknown>>;
type _Action_setCreateTaskAssignedWorkerId = Assert<Assignable<typeof page.setCreateTaskAssignedWorkerId, (...args: any[]) => unknown>>;
type _Handler_handleCreateTaskAssignedWorkerIdChange = Assert<Assignable<typeof page.handleCreateTaskAssignedWorkerIdChange, (...args: any[]) => unknown>>;
type _Action_setCreateTaskAssignedWorkerName = Assert<Assignable<typeof page.setCreateTaskAssignedWorkerName, (...args: any[]) => unknown>>;
type _Handler_handleCreateTaskAssignedWorkerNameChange = Assert<Assignable<typeof page.handleCreateTaskAssignedWorkerNameChange, (...args: any[]) => unknown>>;
type _Action_setCreateTaskBudgetedCost = Assert<Assignable<typeof page.setCreateTaskBudgetedCost, (...args: any[]) => unknown>>;
type _Handler_handleCreateTaskBudgetedCostChange = Assert<Assignable<typeof page.handleCreateTaskBudgetedCostChange, (...args: any[]) => unknown>>;
type _Action_setCreateTaskSequenceNumber = Assert<Assignable<typeof page.setCreateTaskSequenceNumber, (...args: any[]) => unknown>>;
type _Handler_handleCreateTaskSequenceNumberChange = Assert<Assignable<typeof page.handleCreateTaskSequenceNumberChange, (...args: any[]) => unknown>>;
type _Action_setCreateTaskProjectId = Assert<Assignable<typeof page.setCreateTaskProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCreateTaskProjectIdChange = Assert<Assignable<typeof page.handleCreateTaskProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setAssignTaskWorkTaskId = Assert<Assignable<typeof page.setAssignTaskWorkTaskId, (...args: any[]) => unknown>>;
type _Handler_handleAssignTaskWorkTaskIdChange = Assert<Assignable<typeof page.handleAssignTaskWorkTaskIdChange, (...args: any[]) => unknown>>;
type _Action_setAssignTaskAssignedWorkerId = Assert<Assignable<typeof page.setAssignTaskAssignedWorkerId, (...args: any[]) => unknown>>;
type _Handler_handleAssignTaskAssignedWorkerIdChange = Assert<Assignable<typeof page.handleAssignTaskAssignedWorkerIdChange, (...args: any[]) => unknown>>;
type _Action_setAssignTaskAssignedWorkerName = Assert<Assignable<typeof page.setAssignTaskAssignedWorkerName, (...args: any[]) => unknown>>;
type _Handler_handleAssignTaskAssignedWorkerNameChange = Assert<Assignable<typeof page.handleAssignTaskAssignedWorkerNameChange, (...args: any[]) => unknown>>;
type _Action_setAssignTaskDueDate = Assert<Assignable<typeof page.setAssignTaskDueDate, (...args: any[]) => unknown>>;
type _Handler_handleAssignTaskDueDateChange = Assert<Assignable<typeof page.handleAssignTaskDueDateChange, (...args: any[]) => unknown>>;
type _Action_setUpdateTaskWorkTaskId = Assert<Assignable<typeof page.setUpdateTaskWorkTaskId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateTaskWorkTaskIdChange = Assert<Assignable<typeof page.handleUpdateTaskWorkTaskIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateTaskProjectId = Assert<Assignable<typeof page.setUpdateTaskProjectId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateTaskProjectIdChange = Assert<Assignable<typeof page.handleUpdateTaskProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateTaskTitle = Assert<Assignable<typeof page.setUpdateTaskTitle, (...args: any[]) => unknown>>;
type _Handler_handleUpdateTaskTitleChange = Assert<Assignable<typeof page.handleUpdateTaskTitleChange, (...args: any[]) => unknown>>;
type _Action_setUpdateTaskDescription = Assert<Assignable<typeof page.setUpdateTaskDescription, (...args: any[]) => unknown>>;
type _Handler_handleUpdateTaskDescriptionChange = Assert<Assignable<typeof page.handleUpdateTaskDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setUpdateTaskAssignedWorkerId = Assert<Assignable<typeof page.setUpdateTaskAssignedWorkerId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateTaskAssignedWorkerIdChange = Assert<Assignable<typeof page.handleUpdateTaskAssignedWorkerIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateTaskAssignedWorkerName = Assert<Assignable<typeof page.setUpdateTaskAssignedWorkerName, (...args: any[]) => unknown>>;
type _Handler_handleUpdateTaskAssignedWorkerNameChange = Assert<Assignable<typeof page.handleUpdateTaskAssignedWorkerNameChange, (...args: any[]) => unknown>>;
type _Action_setUpdateTaskDueDate = Assert<Assignable<typeof page.setUpdateTaskDueDate, (...args: any[]) => unknown>>;
type _Handler_handleUpdateTaskDueDateChange = Assert<Assignable<typeof page.handleUpdateTaskDueDateChange, (...args: any[]) => unknown>>;
type _Action_setUpdateTaskBudgetedCost = Assert<Assignable<typeof page.setUpdateTaskBudgetedCost, (...args: any[]) => unknown>>;
type _Handler_handleUpdateTaskBudgetedCostChange = Assert<Assignable<typeof page.handleUpdateTaskBudgetedCostChange, (...args: any[]) => unknown>>;
type _Action_setUpdateTaskSequenceNumber = Assert<Assignable<typeof page.setUpdateTaskSequenceNumber, (...args: any[]) => unknown>>;
type _Handler_handleUpdateTaskSequenceNumberChange = Assert<Assignable<typeof page.handleUpdateTaskSequenceNumberChange, (...args: any[]) => unknown>>;

export {};