/// <mls fileReference="_102048_/l1/buildFlowFsm/layer_2_application/usecases/generateStatusReport.defs.ts" enhancement="_blank"/>

export const generateStatusReportUsecase = {
  "schemaVersion": "2026-06-26",
  "artifactType": "usecase",
  "artifactId": "generateStatusReport",
  "moduleName": "buildFlowFsm",
  "status": "draft",
  "source": {
    "agentName": "agentCbUsecase",
    "stepId": 0,
    "planId": ""
  },
  "data": {
    "usecaseId": "generateStatusReport",
    "ports": [
      "StatusReport",
      "Project",
      "WorkTask",
      "MaterialUsage",
      "TimeLog"
    ],
    "functions": [
      {
        "functionName": "generateStatusReport",
        "inputTypeName": "GenerateStatusReportInput",
        "outputTypeName": "GenerateStatusReportOutput",
        "input": [
          {
            "name": "projectId",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "Project identifier from the project detail page route parameter."
          },
          {
            "name": "reportPeriodStart",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "Start date of the reporting period the PM wants the report to cover."
          },
          {
            "name": "reportPeriodEnd",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "End date of the reporting period the PM wants the report to cover."
          }
        ],
        "output": [
          {
            "name": "statusReportId",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "System-generated UUID for the new status report record."
          },
          {
            "name": "projectId",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "Project identifier the report is linked to."
          },
          {
            "name": "status",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "Status of the report, set to 'generated' after creation."
          },
          {
            "name": "content",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "AI-generated plain-language report content produced by the LLM proxy."
          },
          {
            "name": "reportPeriodStart",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "Start date of the reporting period covered by the report."
          },
          {
            "name": "reportPeriodEnd",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "End date of the reporting period covered by the report."
          },
          {
            "name": "generatedAt",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "Timestamp when the LLM proxy generated the report content."
          },
          {
            "name": "llmModelUsed",
            "type": "string",
            "required": false,
            "ofEntity": "StatusReport",
            "description": "Identifier of the LLM model returned by the platform proxy after generation."
          },
          {
            "name": "createdAt",
            "type": "string",
            "required": true,
            "ofEntity": "StatusReport",
            "description": "Record creation timestamp set by the backend."
          }
        ],
        "ports": [
          "StatusReport",
          "Project",
          "WorkTask",
          "TimeLog",
          "MaterialUsage"
        ],
        "rulesApplied": [
          "statusReportAutoGenerated",
          "llmProxyUsage"
        ],
        "transactional": true,
        "steps": [
          "1. Validate that reportPeriodStart <= reportPeriodEnd; if not, throw validation error with rule statusReportAutoGenerated.",
          "2. Load the Project via Project port by projectId; verify it exists and status is 'active'. If not found or not active, throw validation error.",
          "3. Query WorkTask via WorkTask port by projectId to retrieve all tasks for the project.",
          "4. Collect workTaskIds from the WorkTask results and query TimeLog via TimeLog port by workTaskIds, filtering to logs with logDate between reportPeriodStart and reportPeriodEnd and status 'posted'.",
          "5. Query MaterialUsage via MaterialUsage port by projectId, filtering to records with usageDate between reportPeriodStart and reportPeriodEnd and status 'posted'.",
          "6. Compile the WorkTask, TimeLog, and MaterialUsage data into a structured summary covering project progress, costs, and delay risks for the reporting period (rule statusReportAutoGenerated: content is auto-compiled from data, never manually written by the PM).",
          "7. Send the compiled data to the platform LLM proxy (ctx.llm or equivalent platform proxy) to generate plain-language report content (rule llmProxyUsage: the LLM call must go through the platform proxy, not a direct third-party API). Capture the returned content and llmModelUsed from the proxy response.",
          "8. Generate statusReportId via ctx.idGenerator, set generatedAt and createdAt/updatedAt to ctx.clock now.",
          "9. Create the StatusReport record via StatusReport port with status 'generated', the LLM-generated content, llmModelUsed, reportPeriodStart, reportPeriodEnd, generatedAt, createdAt, and updatedAt — all inside a single transaction.",
          "10. Return the created StatusReport fields: statusReportId, projectId, status, content, reportPeriodStart, reportPeriodEnd, generatedAt, llmModelUsed, createdAt."
        ]
      }
    ],
    "mdmRefs": []
  }
} as const;

export default generateStatusReportUsecase;

export const pipeline = [
  {
    "id": "generateStatusReport__applicationUsecase",
    "type": "applicationUsecase",
    "outputPath": "_102048_/l1/buildFlowFsm/layer_2_application/usecases/generateStatusReport.ts",
    "defPath": "_102048_/l1/buildFlowFsm/layer_2_application/usecases/generateStatusReport.defs.ts",
    "dependsFiles": [
      "_102048_/l1/buildFlowFsm/layer_2_application/ports/statusReportRepository.d.ts",
      "_102048_/l1/buildFlowFsm/layer_2_application/ports/projectRepository.d.ts",
      "_102048_/l1/buildFlowFsm/layer_2_application/ports/workTaskRepository.d.ts",
      "_102048_/l1/buildFlowFsm/layer_2_application/ports/materialUsageRepository.d.ts",
      "_102048_/l1/buildFlowFsm/layer_2_application/ports/timeLogRepository.d.ts",
      "_102048_/l1/buildFlowFsm/layer_3_domain/entities/statusReport.d.ts",
      "_102048_/l1/buildFlowFsm/layer_3_domain/entities/project.d.ts",
      "_102048_/l1/buildFlowFsm/layer_3_domain/entities/workTask.d.ts",
      "_102048_/l1/buildFlowFsm/layer_3_domain/entities/materialUsage.d.ts",
      "_102048_/l1/buildFlowFsm/layer_3_domain/entities/timeLog.d.ts"
    ],
    "dependsOn": [],
    "skills": [
      "_102021_/l2/agentChangeBackend/skills/architecture.md",
      "_102021_/l2/agentChangeBackend/skills/applicationUsecase.md",
      "_102034_.d.ts"
    ],
    "agent": "agentCbMaterialize"
  }
] as const;
