/// <mls fileReference="_102048_/l4/workflows/statusReportLifecycle.defs.ts" enhancement="_blank"/>

export const workflowStatusReportLifecycle = {
  "workflowId": "statusReportLifecycle",
  "title": "Status Report Lifecycle",
  "executionMode": "sequential",
  "trigger": "Project manager initiates AI status report generation from the project detail page, compiling tasks, time logs, and material data via the LLM proxy.",
  "actors": [
    "projectManager"
  ],
  "states": [
    "generated",
    "shared"
  ],
  "transitions": [
    {
      "from": "generated",
      "to": "shared",
      "on": "shareStatusReport",
      "by": "projectManager",
      "guard": "Report content has been reviewed by the PM and is ready for client delivery"
    }
  ],
  "operationIds": [
    "generateStatusReport",
    "shareStatusReport"
  ],
  "entities": [
    "StatusReport",
    "Project",
    "WorkTask",
    "TimeLog",
    "MaterialUsage",
    "Client"
  ],
  "rulesApplied": [
    "statusReportAutoGenerated",
    "llmProxyUsage",
    "clientSeesPmStatusReport"
  ],
  "story": {
    "actor": "projectManager",
    "goal": "Produce a professional, plain-language status report from project data and share it with the client so the client stays informed without the PM spending time writing it manually.",
    "steps": [
      "The project manager clicks 'Generate Status Report' on the project detail page so the system compiles tasks, time logs, and material usage into a professional summary using the LLM proxy.",
      "The project manager reviews the generated report to make sure it accurately reflects project progress, costs, and any delay risks before sharing it with the client.",
      "The project manager shares the status report with the client via a shareable link or email so the client has a clear, professional view of where the project stands."
    ],
    "outcome": "A professional status report is generated from real project data and shared with the client, keeping the client informed without manual writing effort."
  },
  "pageId": "statusReportLifecycle",
  "capabilities": [
    {
      "capabilityId": "statusReportLifecycle",
      "title": "Status Report Lifecycle",
      "actor": "projectManager",
      "priority": "now"
    }
  ],
  "statusFrontend": "toCreate",
  "statusBackend": "toCreate"
} as const;

export default workflowStatusReportLifecycle;
